name: app
description: "Ghekko All Platform Flutter Application"
homepage: https://ghekko.nl
publish_to: 'none'
version: 1.0.0

# Windows Config
msix_config:
  display_name: Platform App
  publisher_display_name: Ghekko Dev.
  identity_name: ghekko.platform.app
  msix_version: 1.0.0.0
  logo_path: assets/images/logo-icon.png
  capabilities: internetClient
  languages: en-bg, nl-nl
  store: true

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies updated on 26 nov 2023
dependencies:
  flutter:
    sdk: flutter

  # Platforms
  window_manager: ^0.3.7
  universal_platform: ^1.0.0+1
  macos_ui: ^2.0.2
  macos_window_utils: ^1.4.0
  desktop_window: ^0.4.0
  fluent_ui: ^4.8.2
  system_theme: ^2.3.1
  flutter_acrylic: ^1.1.3

  # Tools
  get: ^4.6.6
  gap: ^3.0.1
  provider: ^6.1.1
  go_router: ^13.0.0

  # Internet Access
  webview_flutter: ^4.4.2
  flutter_macos_webview: ^0.0.6
  url_launcher: ^6.2.1

  # Responsive / Adaptive
  responsive: ^0.3.11+11
  responsive_sizer: ^3.2.0

  # Design
  cupertino_icons: ^1.0.6
  line_icons: ^2.0.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  msix: ^3.16.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/home/
    - assets/images/hammam/
    - assets/images/laseren/
    - assets/images/massage/
    - assets/images/ontharen/
    - assets/images/schoonheid/
    - assets/images/tanden/
  fonts:
    - family: Electric Toaster
      fonts:
        - asset: assets/fonts/Electric/electric.ttf
        - asset: assets/fonts/Electric/electric.ttf
          weight: 500
        - asset: assets/fonts/Electric/electric.ttf
          weight: 600
        - asset: assets/fonts/Electric/electric.ttf
          weight: 700
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee/Bungee-Regular.ttf
        - asset: assets/fonts/Bungee/Bungee-Regular.ttf
          weight: 500
        - asset: assets/fonts/Bungee/Bungee-Regular.ttf
          weight: 600
        - asset: assets/fonts/Bungee/Bungee-Regular.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800